version: '3.8'

services:
  web:
    build: .
    # 컨테이너가 실행될 때 외부로 5000번 포트를 노출합니다.
    # 예시: 로컬 컴퓨터의 5000번 포트와 컨테이너 내부의 5000번 포트를 연결합니다.
    ports:
      - "5000:5000"
    # 컨테이너가 예상치 못하게 종료될 경우 재시작하도록 설정
    restart: always